/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Counter } from './Counter.js';
export type { KrishiPassport } from './KrishiPassport.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export { KrishiPassport__factory } from './factories/KrishiPassport__factory.js';