/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface KrishiPassportInterface extends Interface {
    getFunction(nameOrSignature: "createPassport" | "passportCount" | "passports" | "verifyPassport"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PassportCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createPassport', values: [string]): string;
encodeFunctionData(functionFragment: 'passportCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'passports', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyPassport', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createPassport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passportCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passports', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyPassport', data: BytesLike): Result;
  }

  
    export namespace PassportCreatedEvent {
      export type InputTuple = [id: BigNumberish, farmer: AddressLike, dataHash: string];
      export type OutputTuple = [id: bigint, farmer: string, dataHash: string];
      export interface OutputObject {id: bigint, farmer: string, dataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KrishiPassport extends BaseContract {
    
    connect(runner?: ContractRunner | null): KrishiPassport;
    waitForDeployment(): Promise<this>;

    interface: KrishiPassportInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createPassport: TypedContractMethod<
      [_hash: string, ],
      [void],
      'nonpayable'
    >
    

    
    passportCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    passports: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, boolean] & {id: bigint, farmer: string, dataHash: string, timestamp: bigint, active: boolean }],
      'view'
    >
    

    
    verifyPassport: TypedContractMethod<
      [_id: BigNumberish, ],
      [[string, string, bigint, boolean]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createPassport'): TypedContractMethod<
      [_hash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'passportCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'passports'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, boolean] & {id: bigint, farmer: string, dataHash: string, timestamp: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'verifyPassport'): TypedContractMethod<
      [_id: BigNumberish, ],
      [[string, string, bigint, boolean]],
      'view'
    >;

    getEvent(key: 'PassportCreated'): TypedContractEvent<PassportCreatedEvent.InputTuple, PassportCreatedEvent.OutputTuple, PassportCreatedEvent.OutputObject>;

    filters: {
      
      'PassportCreated(uint256,address,string)': TypedContractEvent<PassportCreatedEvent.InputTuple, PassportCreatedEvent.OutputTuple, PassportCreatedEvent.OutputObject>;
      PassportCreated: TypedContractEvent<PassportCreatedEvent.InputTuple, PassportCreatedEvent.OutputTuple, PassportCreatedEvent.OutputObject>;
    
    };
  }