# Generated by Django 6.0.1 on 2026-02-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='QualityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField()),
                ('freshness_score', models.FloatField()),
                ('color_saturation', models.FloatField(blank=True, null=True)),
                ('surface_defects', models.JSONField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qualitymetrics',
            },
        ),
        migrations.CreateModel(
            name='ProduceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produce_images/')),
                ('passport_id', models.CharField(max_length=100, unique=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('on_chain_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
                ('metrics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.qualitymetrics')),
            ],
            options={
                'db_table': 'producerecord',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('produce_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producerecord')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
